# Generated by Django 4.2.5 on 2023-09-29 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_remove_post_likes_postlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='likes',
        ),
    ]
